### ISSUE TITLE
Add a "commit and refresh" or "split off new metaball

### ISSUE THREAD

**Issue by patmo141** [bblanimation/wax_dropper#2] opened 2019-02-02 22:38 UTC
As the cost of recalculating the whole wax object grows, give the option to "commit and refresh"

one way of doing this is to switch to scene.ray_cast, and just keep temp meshes around
Keep metaball objects around, but have unique names

At the end, merge all the metaball objects together at the metaball level
Recreate mesh
finish up the commit

**Comment by bblanimation** [comment] 2019-03-25 20:36
Duplicate of issue #3

**Closed by bblanimation** 2019-03-25 20:36 UTC
